# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ArrayUtilizer.o
LINKOBJ  = ArrayUtilizer.o
LIBS     = -L"D:/Program Development/Dev-Cpp/MinGW64/lib" -L"D:/Program Development/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Program Development/Dev-Cpp/MinGW64/include" -I"D:/Program Development/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Program Development/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Program Development/Dev-Cpp/MinGW64/include" -I"D:/Program Development/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Program Development/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Program Development/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

ArrayUtilizer.o: ArrayUtilizer.cpp
	$(CPP) -c ArrayUtilizer.cpp -o ArrayUtilizer.o $(CXXFLAGS)
